### ISSUE TITLE
Landing page & Learn more page copywriting

### ISSUE THREAD

**Issue by yoon-bbox** [BalloonBox-Inc/near-oracle-client#30]
We need some content to add on the landing page & learn more page. 
Should we keep the same template from SCRTsibyl? 

https://docs.google.com/document/d/1GxDBH37LbQkNq2xqyhRi8BXsCTHiEAbhsFFcLbm02x8/edit?usp=sharing

**Comment by irene-bbox** [comment]
Just created a new template with content for both pages (landing page & learn page) -- see Gdoc.
